unit TestuPareto;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

interface

uses
  TestFramework, uPareto, System.Generics.Collections;

type
  // Test methods for class TParetoItem

  TestTParetoItem = class(TTestCase)
  strict private
    FParetoItem: TParetoItem;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  end;
  // Test methods for class TPareto

  TestTPareto = class(TTestCase)
  strict private
    FPareto: TPareto;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure НесравнимыеЗначения;
    procedure НесравнимыеЗначения2;
    procedure А_Больше_Б;
    procedure А_Меньше_Б;
    procedure ОдинаковыеЗначения;
    Procedure Сжатие;
  end;

implementation

procedure TestTParetoItem.SetUp;
begin
  FParetoItem := TParetoItem.Create(5, 5, 'Test');
end;

procedure TestTParetoItem.TearDown;
begin
  FParetoItem.Free;
  FParetoItem := nil;
end;

procedure TestTPareto.SetUp;
begin
  FPareto := TPareto.Create;
  FPareto.AddRange([ //
    TParetoItem.Create(1, 5, '1'), // 0
    TParetoItem.Create(2, 4, '2'), // 1
    TParetoItem.Create(3, 3, '3'), // 2
    TParetoItem.Create(4, 2, '4'), // 3
    TParetoItem.Create(5, 1, '5'), // 4
    TParetoItem.Create(3, 3, '6') // 5

    { } ]);
end;

procedure TestTPareto.TearDown;
begin
  FPareto.Free;
  FPareto := nil;
end;

procedure TestTPareto.А_Больше_Б;
begin
  FPareto.MaxA := False;
  FPareto.MaxB := True;
  CheckTrue(FPareto.Compare(0, 1) = TParetoResult.RESULT_BIGER);
end;

procedure TestTPareto.НесравнимыеЗначения;
begin
  FPareto.MaxA := True;
  FPareto.MaxB := True;
  CheckTrue(FPareto.Compare(0, 1) = TParetoResult.RESULT_INCOMPARABLY);
end;

procedure TestTPareto.НесравнимыеЗначения2;
begin
  FPareto.MaxA := False;
  FPareto.MaxB := False;
  CheckTrue(FPareto.Compare(0, 1) = TParetoResult.RESULT_INCOMPARABLY);
end;

procedure TestTPareto.А_Меньше_Б;
begin
  FPareto.MaxA := True;
  FPareto.MaxB := False;
  CheckTrue(FPareto.Compare(0, 1) = TParetoResult.RESULT_SMALLER);
end;

procedure TestTPareto.ОдинаковыеЗначения;
begin
  FPareto.MaxA := True;
  FPareto.MaxB := False;
  CheckTrue(FPareto.Compare(2, 5) = TParetoResult.RESULT_INCOMPARABLY);
end;

procedure TestTPareto.Сжатие;
begin
  FPareto.Compress;
end;

initialization

// Register any test cases with the test runner
RegisterTest(TestTParetoItem.Suite);
RegisterTest(TestTPareto.Suite);

end.
